// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return window.myFlux = new flux.slider('#slider', {
      pagination: false,
      transitions: ['blocks'],
      delay: 5000
    });
  });

}).call(this);
